### ISSUE TITLE
Errors in console when hitting end crystals or fireballs

### ISSUE THREAD

**Issue by just-dev-creator** [explorethebuild/etb2-cosmetics-event#3]
Following error in displayed in console:
```
[20:03:19] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to Etb2CosmeticsEvent v0.1
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftLargeFireball cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_16_R3.entity.CraftLargeFireball and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
	at dev.just.etb2cosmeticsevent.listeners.MobKillListener.onMobKill(MobKillListener.kt:17) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-509]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1118) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1108) ~[patched_1.16.5.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1104) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.EntityFireball.damageEntity(EntityFireball.java:162) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1085) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:1859) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2251) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1205) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-509]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-509]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by just-dev-creator** [comment]
A return was missing in living entity check
